### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by Melkor82** [gurbyz/custom-cards-lovelace#15]
**Which card does give you issues?**
power-wheel-card

**Which version of HA do you use?**
Example: 0.88.2

**Which version of the card do you use?**
Example: 0.0.10

**Describe the bug**
http://xxx.xxx.xxx.xxx:8123/local/power-wheel-card.js?v=1:7:27 Uncaught TypeError: Cannot convert undefined or null to object 

**Configuration of the card**
```
      - color_icons: true
        grid_power_consumption_entity: sensor.fv_import
        grid_power_production_entity: sensor.fv_export
        power_decimals: 2
        solar_power_entity: sensor.fv_produzione
        title: Fotovoltaico
        type: 'custom:power-wheel-card'
```

**Developer console debug output**
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at power-wheel-card.js?v=1:7

**Expected behavior**
For the custom card to work :)

**Additional context**
I had it briefly working then tried to add energy view. After broking functionality i tried to come back but was not working anymore

**Comment by gurbyz** [comment]
It looks like the home-assistant-main custom element isn’t loaded in your home assistant UI. But that probably doesn’t help you much ;-)  Are all other views, cards, etc displaying normally? Are there errors e.g. of other cards in the dev console of your browser?

**Comment by gurbyz** [comment]
Hi Marco, did you re-copy or edit the file`power-wheel-card.js` in the attempt to bring back to live the card and maybe made a mistake with it? Because if I reproduce the error, the error should be in line 10, not in line 7. It seems there is something missing in your file.

Could you please re-copy the file from GitHub to HA and use the Raw button in GitHub? Then you end up with this page: https://raw.githubusercontent.com/gurbyz/custom-cards-lovelace/master/power-wheel-card/power-wheel-card.js Then you can do a much more clean copy.

**Comment by Melkor82** [comment]
Sorry, i was away for the weekend. I copied the raw version and updated to v=2 and now it is working. 
Thank you!

**Comment by gurbyz** [comment]
Super!
